# Shared tool registration and rule generation helpers. Loading writes nothing.
$script:ToolchainConfigPath = Join-Path $script:ProjectRoot '.codex\toolchain.local.json'
$script:LocalRulesPath = Join-Path $script:ProjectRoot '.codex\rules\local-toolchain.rules'

function Get-ToolWrapperNames {
    @('run-godot.ps1', 'run-network.ps1', 'run-exported.ps1', 'run-blender.ps1',
        'run-mcp.ps1', 'run-validation.ps1', 'inspect-cursor.ps1',
        'cleanup-project-processes.ps1', 'verify-permissions.ps1')
}

function Get-RuleShellNames {
    @('powershell.exe', 'powershell', (Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'))
}

function Get-LocalRulesText {
    param([string]$ProjectRoot = $script:ProjectRoot)
    $shells = ConvertTo-Json -InputObject @(Get-RuleShellNames) -Compress
    $lines = @('# Generated by setup-local.ps1; machine-local, do not commit.', '')
    foreach ($name in @(Get-ToolWrapperNames)) {
        $quotedPath = ConvertTo-Json -InputObject ([IO.Path]::Combine($ProjectRoot, 'tools\codex', $name)) -Compress
        $lines += @(
            'prefix_rule(',
            ('    pattern = [' + $shells + ', "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", ' + $quotedPath + '],'),
            '    decision = "allow",',
            ('    justification = "Run the fixed project wrapper ' + $name + '.",'),
            ')', ''
        )
    }
    return ($lines -join [Environment]::NewLine)
}

function Read-ToolchainConfig {
    param([switch]$AllowMissing, [switch]$AllowMoved)
    if (-not (Test-Path -LiteralPath $script:ToolchainConfigPath -PathType Leaf)) {
        if ($AllowMissing) { return $null }
        throw 'Toolchain is not configured. Run tools/codex/setup-local.ps1 first.'
    }
    $config = Get-Content -Raw -LiteralPath $script:ToolchainConfigPath -Encoding UTF8 | ConvertFrom-Json
    foreach ($field in @('SchemaVersion', 'ProjectRoot', 'GodotPath', 'BlenderPath', 'BlenderMcpPath')) {
        if ($config.PSObject.Properties.Name -notcontains $field) {
            throw "Invalid toolchain configuration: missing $field. Run setup-local.ps1 again."
        }
    }
    if ($config.SchemaVersion -ne 1) { throw 'Unsupported toolchain SchemaVersion.' }
    if (-not $AllowMoved -and -not [string]::Equals($config.ProjectRoot, $script:ProjectRoot, [StringComparison]::OrdinalIgnoreCase)) {
        throw 'The project has moved. Run setup-local.ps1 again to regenerate paths and rules.'
    }
    return $config
}

function Resolve-ToolExecutable {
    param(
        [ValidateSet('Godot', 'Blender', 'BlenderMcp')][string]$Tool,
        [Parameter(Mandatory = $true)][string]$Path
    )
    if (-not [IO.Path]::IsPathRooted($Path)) { throw "$Tool path must be absolute: $Path" }
    $pattern = switch ($Tool) {
        Godot { '^godot[^\\/]*\.exe$' }
        Blender { '^blender\.exe$' }
        BlenderMcp { '^blender-mcp\.exe$' }
    }
    if ([IO.Path]::GetFileName($Path) -notmatch $pattern -or -not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "$Tool executable is missing or invalid: $Path. Run setup-local.ps1 with an explicit path."
    }
    return (Resolve-Path -LiteralPath $Path).ProviderPath
}

function Get-RegisteredToolPath {
    param(
        [ValidateSet('Godot', 'Blender', 'BlenderMcp')][string]$Tool,
        [string]$RequestedPath
    )
    $config = Read-ToolchainConfig
    $registered = [string]$config.($Tool + 'Path')
    if (-not $registered) { throw "$Tool is not configured. Run setup-local.ps1 -$($Tool)Path <executable>." }
    $resolved = Resolve-ToolExecutable -Tool $Tool -Path $registered
    if ($RequestedPath) {
        $requested = Resolve-ToolExecutable -Tool $Tool -Path $RequestedPath
        if (-not [string]::Equals($resolved, $requested, [StringComparison]::OrdinalIgnoreCase)) {
            throw "$Tool path is not registered. Change it through setup-local.ps1 first."
        }
    }
    return $resolved
}

function Select-ToolCandidate {
    param([string]$Tool, [string[]]$Candidates = @())
    $valid = @(@(
        foreach ($candidate in $Candidates) {
            if (-not $candidate) { continue }
            try { Resolve-ToolExecutable -Tool $Tool -Path $candidate } catch { continue }
        }
    ) | Sort-Object -Unique)
    if ($Tool -eq 'Godot') {
        # Prefer a console companion of the same binary, not another version.
        $valid = @($valid | Where-Object {
            $companion = [IO.Path]::ChangeExtension($_, $null).TrimEnd('.') + '_console.exe'
            $_ -match '_console\.exe$' -or $valid -notcontains $companion
        })
    }
    if ($valid.Count -gt 1) {
        throw "Multiple $Tool installations found. Pass -$($Tool)Path explicitly: $($valid -join '; ')"
    }
    if ($valid.Count -eq 1) { return $valid[0] }
    return $null
}

function Find-ToolsInDirectories {
    param([string]$Tool, [string[]]$Roots = @(), [int]$Depth = 2)
    $filter = switch ($Tool) {
        Godot { 'Godot*.exe' }
        Blender { 'blender.exe' }
        BlenderMcp { 'blender-mcp.exe' }
    }
    $pending = @($Roots | Where-Object { $_ -and (Test-Path -LiteralPath $_ -PathType Container) } | Sort-Object -Unique)
    for ($level = 0; $level -le $Depth -and $pending.Count -gt 0; $level++) {
        $next = @()
        foreach ($directory in $pending) {
            $item = Get-Item -LiteralPath $directory -Force -ErrorAction SilentlyContinue
            if (-not $item -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) { continue }
            Get-ChildItem -LiteralPath $directory -Filter $filter -File -Force -ErrorAction SilentlyContinue |
                Where-Object { -not ($_.Attributes -band [IO.FileAttributes]::ReparsePoint) } |
                ForEach-Object { $_.FullName }
            if ($level -lt $Depth) {
                $next += @(Get-ChildItem -LiteralPath $directory -Directory -Force -ErrorAction SilentlyContinue |
                    Where-Object { -not ($_.Attributes -band [IO.FileAttributes]::ReparsePoint) } |
                    ForEach-Object { $_.FullName })
            }
        }
        $pending = @($next)
    }
}

function Find-LocalTool {
    param([string]$Tool, [string]$ExplicitPath, [string]$ExistingPath, [string[]]$SearchRoot = @())
    if ($ExplicitPath) { return Resolve-ToolExecutable -Tool $Tool -Path $ExplicitPath }
    if ($ExistingPath) {
        try { return Resolve-ToolExecutable -Tool $Tool -Path $ExistingPath } catch {
            Write-Warning "Saved $Tool installation is unavailable; searching again."
        }
    }
    $pathDirectories = @($env:Path.Split(';') | Where-Object { $_ })
    $found = Select-ToolCandidate -Tool $Tool -Candidates @(Find-ToolsInDirectories -Tool $Tool -Roots $pathDirectories -Depth 0)
    if ($found) { return $found }

    $installRoots = @()
    foreach ($registryRoot in @('HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall',
        'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall',
        'HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall')) {
        foreach ($entry in @(Get-ChildItem -LiteralPath $registryRoot -ErrorAction SilentlyContinue)) {
            $info = Get-ItemProperty -LiteralPath $entry.PSPath -ErrorAction SilentlyContinue
            if ($info -and $info.PSObject.Properties.Name -contains 'DisplayName' -and
                $info.DisplayName -match $Tool -and $info.PSObject.Properties.Name -contains 'InstallLocation') {
                $installRoots += $info.InstallLocation
            }
        }
    }
    foreach ($base in @($env:ProgramFiles, [Environment]::GetEnvironmentVariable('ProgramFiles(x86)'), (Join-Path $env:LOCALAPPDATA 'Programs'))) {
        if (-not $base -or -not (Test-Path -LiteralPath $base -PathType Container)) { continue }
        $installRoots += @(Get-ChildItem -LiteralPath $base -Directory -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -match 'Godot|Blender' } | ForEach-Object { $_.FullName })
    }
    $found = Select-ToolCandidate -Tool $Tool -Candidates @(Find-ToolsInDirectories -Tool $Tool -Roots $installRoots -Depth 3)
    if ($found) { return $found }
    return Select-ToolCandidate -Tool $Tool -Candidates @(Find-ToolsInDirectories -Tool $Tool -Roots $SearchRoot -Depth 4)
}

function Assert-LocalRulesCurrent {
    if (-not (Test-Path -LiteralPath $script:LocalRulesPath -PathType Leaf)) {
        throw 'Local rules are missing. Run setup-local.ps1 and restart Codex.'
    }
    $actual = [IO.File]::ReadAllText($script:LocalRulesPath).Replace([string][char]13, '').TrimEnd()
    $expected = (Get-LocalRulesText).Replace([string][char]13, '').TrimEnd()
    if ($actual -cne $expected) {
        throw 'Local rules are stale or modified. Review setup-local.ps1 -CheckOnly, then regenerate and restart Codex.'
    }
}
